###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.6
      networks:
        app_net:
          ipv4_address: 172.25.0.2
      container_name: zcms-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "8003:3306"

    webserver:
      image: nginx:alpine
      container_name: zcms-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8001:80"
      networks:
        app_net:
          ipv4_address: 172.25.0.4

    phantomjs:
        image: shufo/phantomjs
        extra_hosts:
            - ${DOMAIN}:172.25.0.4
        command: --webdriver 4444
        ports:
          - 4444:4444
        networks:
            app_net:
              ipv4_address: 172.25.0.5


    php-fpm:
      build: phpdocker/php-fpm
      container_name: zcms-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

      networks:
        app_net:
          ipv4_address: 172.25.0.3

    mailcatcher:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025
        networks:
          app_net:
            ipv4_address: 172.25.0.6


networks:
  app_net:
      driver: bridge
      ipam:
        config:
          - subnet: 172.25.0.0/24
