imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    supported_lang: ['en', 'fr']
    admin_path: admin


framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%", fr] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        #handler_id:  session.handler.native_file
        handler_id: ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        supported_lang: %supported_lang%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true


doctrine_migrations:
    dir_name: "%kernel.root_dir%/../src/AppBundle/DoctrineMigrations"
    namespace: AppBundle\DoctrineMigrations
    table_name: migration_versions
    name: AppBundle Migrations
    organize_migrations: false # Version >=1.2 Possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false




# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: AppBundle\Entity\User
  from_email:
    address: admin@zcms.test
    sender_name: "zcms admin"

easy_admin:
    site_name: ZCMS
    entities:
        User:
            class: AppBundle\Entity\User
            controller: AppBundle\Controller\AdminController
            label: admin.link.user_managment
            # for new user
            new:
                fields:
                    - username
                    - firstname
                    - lastname
                    - { property: 'plainPassword', type: 'repeated', type_options: { type: 'Symfony\Component\Form\Extension\Core\Type\PasswordType', required: false, first_options: { label: 'Password'}, second_options: { label: 'Repeat Password'}, invalid_message: 'The password fields must match.' }}
                    - { property: 'email', type: 'email', type_options: { trim: true } }
                    - roles
                    - enabled
            show:
                actions: ['edit', '-delete', '-list']
                fields:
                    - id
                    - username
                    - firstname
                    - lastname
                    - email
                    - roles
                    - enabled
                    - { property: 'last_login', type: 'datetime' }
                    - modified
                    - created
            edit:
                actions: ['-delete', '-list']
                fields:
                    - username
                    - firstname
                    - lastname
                    - { property: 'plainPassword', type: 'repeated', type_options: { type: 'Symfony\Component\Form\Extension\Core\Type\PasswordType', required: false, first_options: { label: 'Password'}, second_options: { label: 'Repeat Password'}, invalid_message: 'The password fields must match.' }}
                    - { property: 'email', type: 'email', type_options: { trim: true } }
                    - roles
                    - enabled
            list:
                title: 'User listing'
                actions: ['show']
                fields:
                    - id
                    - username
                    - email
                    - firstname
                    - lastname
                    - enabled
                    - roles
                    - { property: 'last_login', type: 'datetime' }


